// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkkbjxerklshrxiocnny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra2JqeGVya2xzaHJ4aW9jbm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDkzOTIsImV4cCI6MjA2ODM4NTM5Mn0.9PAO4EGu9m_kda_2LOM4FNiyqBvGRurFkjz2dYICKUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});